apiVersion: ansible.crossplane.io/v1alpha1
kind: PlaybookSet
metadata:
  name: example
spec:
  forProvider:
    # PlaybookSet default to using a remote source - like playbookSet-remote.yaml.
    # For simple cases you can use an inline source to specify the content of
    # playbook.yaml as opaque, inline yaml.
    source: Inline
    module: |
      - name: create a bucket
        hosts: localhost
        tasks:
          - name: Storage bucket
            google.cloud.gcp_storage_bucket:
              name: ansible-storage-module
              project: project-id
              auth_kind: serviceaccount
              service_account_file: "gcp-credentials.json"
              state: present
  providerConfigRef:
    name: default