apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-ansible
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: provider-ansible
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      The Ansible Crossplane provider adds support for
      managing Ansible resources in Kubernetes.

spec:
  controller:
    image: DOCKER_REGISTRY/provider-ansible:VERSION
