apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-ansible
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: crossplane-provider-ansible
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A template that can be used to create Crossplane providers.

spec:
  controller:
    image: DOCKER_REGISTRY/crossplane-provider-ansible:VERSION
